//Arrow Functions - não precisa da palavra function

const somando = ()=> console.log("Isso é uma ARROW FUNCTION"); //quando tem uma linha, não precisa de chaves

somando();

const somandoDois = numeroDois => console.log("Isso é uma ARROW FUNCTION que recebeu o numeor " + numeroDois); //quando tem uma linha, não precisa de chaves

somandoDois(10);

//com mais de um parametro, temos que usar os (). Caso tenhamos mais de uma linha, teremos que usar {}
